-- phpMyAdmin SQL Dump
-- version 4.9.0.1
-- https://www.phpmyadmin.net/
--
-- Host: sql306.infinityfree.com
-- Generation Time: Jul 27, 2026 at 04:06 AM
-- Server version: 11.4.12-MariaDB
-- PHP Version: 7.2.22

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `if0_42478964_cai`
--

-- --------------------------------------------------------

--
-- Table structure for table `products`
--

CREATE TABLE `products` (
  `id` int(11) NOT NULL,
  `category_id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `slug` varchar(255) NOT NULL,
  `sku` varchar(100) DEFAULT NULL,
  `item_code` varchar(100) DEFAULT NULL,
  `catalog` varchar(100) DEFAULT NULL,
  `series` varchar(100) DEFAULT NULL,
  `description` longtext DEFAULT NULL,
  `material` varchar(100) DEFAULT NULL,
  `shape` varchar(100) DEFAULT NULL,
  `color` varchar(100) DEFAULT NULL,
  `finish` varchar(100) DEFAULT NULL,
  `thumbnail` varchar(255) DEFAULT NULL,
  `featured` tinyint(1) DEFAULT 0,
  `status` tinyint(1) DEFAULT 1,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `products`
--

INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sku`, `item_code`, `catalog`, `series`, `description`, `material`, `shape`, `color`, `finish`, `thumbnail`, `featured`, `status`, `created_at`, `updated_at`) VALUES
(1, 8, 'White Architectural GRC Jali', 'white-architectural-grc-jali', '', '', '', '', 'Premium White GRC Jali manufactured using high-grade Glass Reinforced Concrete. Ideal for luxury building façades, balconies, compound walls, and striking architectural elevations. Highly lightweight, durable, and suitable for both indoor and outdoor applications.', 'Glass Reinforced Concrete', '', 'Terracotta / Light Red Sandstone', 'Smooth Matte', 'images/products/grc/grc1.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(2, 8, 'Geometric Cube GRC Jali (100mm)', 'geometric-cube-grc-jali-100mm', '', '', '', '', 'A modern geometric GRC Jali showcasing a cubical matrix. Designed for cutting-edge contemporary architectural projects, this pattern provides exceptional ventilation and unique shadow-casting while keeping modern structures cool.', 'Glass Reinforced Concrete', '', 'Natural Cement Grey / Cool Slate Grey', 'Concrete Raw Finish', 'images/products/grc/grc2.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(3, 8, 'Islamic Lattice GRC Jali (100mm)', 'islamic-lattice-grc-jali-100mm', '', '', '', '', 'Features a classic, intricate Islamic geometric star-and-lattice layout. This highly artistic GRC panel brings a traditional heritage touch to modern mosques, premium villas, and spiritual institutional architectures.', 'Glass Reinforced Concrete', '', 'Off-White / Cream', 'Fine Sandblast', 'images/products/grc/grc3.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(4, 8, 'Diamond Mesh GRC Jali (100mm)', 'diamond-mesh-grc-jali-100mm', '', '', '', '', 'An elegant, continuous diamond crisscross pattern that provides a perfect balance of privacy and natural illumination. Excellent choice for multi-story office building exteriors and residential balcony panels.', 'Glass Reinforced Concrete', '', 'Off-White / Crisp White', 'Natural Exposed Concrete', 'images/products/grc/grc4.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(5, 8, 'Contemporary Square GRC Jali (100mm)', 'contemporary-square-grc-jali-100mm', '', '', '', '', 'Symmetrical modern grid layout optimized for clean lines and high-speed air circulation. Highly suitable for structural ventilation ducts, HVAC shafts, parking lot screens, and loft interior partitions.', 'Glass Reinforced Concrete', '', 'Terracotta / Light Red Sandstone', 'Smooth Concrete', 'images/products/grc/grc5.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(6, 8, 'Linear Stripes GRC Jali (100mm)', 'linear-stripes-grc-jali-100mm', '', '', '', '', 'Features clean, repetitive parallel linear cutouts. Acts as a brilliant architectural sunshade/louver system that reduces indoor HVAC cooling loads by cutting down direct solar heat gain.', 'Glass Reinforced Concrete', '', 'Off-White / Ivory White', 'Acid Washed', 'images/products/grc/grc6.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(7, 8, 'Classic Cross GRC Jali (100mm)', 'classic-cross-grc-jali-100mm', '', '', '', '', 'A classic cross (X-pattern) layout reminiscent of vintage colonial structures and Mediterranean villas. Blends effortlessly with earthy landscape stones and rustic boundary wall designs.', 'Glass Reinforced Concrete', '', 'Muted Mustard Yellow / Ochre', 'Textured Stone Finish', 'images/products/grc/grc7.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(8, 8, 'Star Matrix GRC Jali (100mm)', 'star-matrix-grc-jali-100mm', '', '', '', '', 'A dense, geometric arrangement of interlocking stars. Specifically engineered as an accent design element for luxurious hotel lobbies, wedding venues, and high-profile residential entry structures.', 'Glass Reinforced Concrete', '', 'Pure White', 'Satin Smooth', 'images/products/grc/grc8.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(9, 8, 'Hexagonal Cellular GRC Jali (100mm)', 'hexagonal-cellular-grc-jali-100mm', '', '', '', '', 'An organic, honeycomb-inspired cell pattern. Combining biophilic design principles with structural concrete durability, it is highly favored for certified green building designs and IT park installations.', 'Glass Reinforced Concrete', '', 'Beige / Light Sandstone', 'Industrial Matte', 'images/products/grc/grc9.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(10, 3, 'Classic Park Concrete Bench', 'classic-park-concrete-bench-without-arm-rest', '', '', '', '', 'Premium precast concrete bench manufactured for traditional outdoor parks, public gardens, and open landscapes. Designed with an ergonomic backrest for comfortable public seating and long-lasting elemental durability.', 'Precast Concrete', '', 'Granite Grey', 'Smooth Matte', 'images/products/benches/bench1.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(11, 3, 'Executive Slatted Concrete Bench', 'executive-slatted-concrete-bench-with-arm-rest', '', '', '', '', 'Heavy-duty precast concrete bench with integrated armrests and structured slat-back design. Perfect choice for elite commercial property entries, urban spaces, corporate courtyards, and premium residential layouts.', 'Precast Concrete', '', 'Grey / Lime Green', 'Slatted Textured', 'images/products/benches/bench2.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(12, 3, 'Contemporary Garden Concrete Bench', 'contemporary-garden-concrete-bench', '', '', '', '', 'Sleek and minimalist modern concrete bench curated explicitly for high-end boutique hotels, modern residential villa lawns, and contemporary architecture landscapes.', 'Precast Concrete', '', 'Dark Blue / Navy', 'Polished Gloss', 'images/products/benches/bench3.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(13, 3, 'Urban Landscape Concrete Bench', 'urban-landscape-concrete-bench', '', '', '', '', 'Robust structural bench engineered to withstand massive daily foot traffic loads in metro stations, public plazas, urban streetscapes, and busy downtown walkways.', 'Precast Concrete', '', 'Light Purple / Lavender', 'Industrial Rough', 'images/products/benches/bench4.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(14, 3, 'Traditional Boulevard Concrete Bench', 'traditional-boulevard-concrete-bench', '', '', '', '', 'Features a classic European boulevard aesthetic with a warm terracotta clay tint color profile. Perfectly fits heritage pathways, walking trails, and botanical gardens.', 'Precast Concrete', '', 'Dark Slate Grey / Teal Grey', 'Rustic Matte', 'images/products/benches/bench5.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(15, 3, 'Modernist Plaza Concrete Bench', 'modernist-plaza-concrete-bench', '', '', '', '', 'Features a striking geometric presentation with an acid-washed finish texture that reveals subtle underlying aggregates. Enhances museums, high-tech parks, and corporate plazas.', 'Precast Concrete', '', 'Bright Orange', 'Acid Washed', 'images/products/benches/bench6.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(16, 3, 'Ornate Heritage Concrete Bench', 'ornate-heritage-concrete-bench', '', '', '', '', 'Designed with deep artistic moldings on the structural legs and back frame panel, echoing old-world luxury Indian palace architectural patterns.', 'Precast Concrete', '', 'Dark Greyish-Brown', 'Intricately Molded Antique', 'images/products/benches/bench7.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(17, 3, 'Rustic Parkside Concrete Bench', 'rustic-parkside-concrete-bench', '', '', '', '', 'Offers the warm, traditional visual appeal of a thick natural timber plank structure combined with the lifetime permanence and zero-rot capability of reinforced precast concrete.', 'Precast Concrete', '', 'Turquoise / Aqua Teal', 'Faux Wood-Grain Textured', 'images/products/benches/bench8.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(18, 3, 'Eco-Lite Garden Concrete Bench', 'eco-lite-garden-concrete-bench', '', '', '', '', 'A smart, cost-effective lightweight concrete composite model variation designed for easy shifting and flexible backyard installations without needing crane cranes or heavy crews.', 'Lightweight Precast Composite', '', 'Dark Timber Brown', 'Smooth Pored Fine Finish', 'images/products/benches/bench9.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(19, 3, 'Vista Point Concrete Bench', 'vista-point-concrete-bench', '', '', '', '', 'Perfect seating match for high altitude mountain view points, coastal marine drive promenades, and scenic highway overlook stops.', 'Precast Concrete', '', 'Dark Timber Brown', 'Polished Terrazzo Style', 'images/products/benches/bench10.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(20, 3, 'Compact Courtyard Concrete Bench', 'compact-courtyard-concrete-bench', '', '', '', '', 'A specially shortened spatial layout design configuration optimized for tight urban balconies, small rooftop gardens, patio paths, and narrow home courtyard corners.', 'Precast Concrete', '', 'Dark Timber Brown', 'Satin Soft Finish', 'images/products/benches/bench11.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(21, 3, 'Metro Transit Concrete Bench', 'metro-transit-concrete-bench', '', '', '', '', 'Utility grade infrastructure bench with anti-graffiti top layering designed intentionally for bus terminals, train railway platforms, and public transport interchanges.', 'Precast Concrete', '', 'Muted Purple-Brown / Mahogany', 'Ultra Smooth Anti-graffiti', 'images/products/benches/bench12.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(22, 3, 'Meadow View Concrete Bench', 'meadow-view-concrete-bench', '', '', '', '', 'Features organic styling curves and muted raw earth blend coloration to disappear effortlessly into natural farmhouse orchards, large meadows, and organic fields.', 'Precast Concrete', '', 'Reddish Brown / Terracotta', 'Natural Textured', 'images/products/benches/bench13.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(23, 3, 'Commercial Promenade Concrete Bench', 'commercial-promenade-concrete-bench', '', '', '', '', 'Premium industrial grade shopping mall boardwalk seating. Clean lines with a micro quartz particle reflective configuration that shimmers under nighttime public streetlights.', 'Precast Concrete', '', 'Dark Timber Brown', 'Semi-gloss Fine aggregate', 'images/products/benches/bench14.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(24, 3, 'Minimalist Esplanade Concrete Bench', 'minimalist-esplanade-concrete-bench', '', '', '', '', 'Eliminates all visual clutter. A perfectly balanced crisp design offering high performance minimal profiles ideal for open art exhibition lawns and upscale smart-city spaces.', 'Precast Concrete', '', 'Dark Charcoal Grey / Timber Brown', 'Ultra Fine Sandblast', 'images/products/benches/bench15.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(25, 3, 'Botanical Sanctuary Concrete Bench', 'botanical-sanctuary-concrete-bench', '', '', '', '', 'Tailored visually for floral hot-houses, botanical sanctuaries, and private rose gardens. Coloration prevents high glare under direct bright greenhouse solar glass arrays.', 'Precast Concrete', '', 'Natural Cement Grey / Light Grey', 'Soft Leaf Stamped Texture', 'images/products/benches/bench16.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(26, 6, 'FRP Elephant Statue', 'frp-elephant-statue', '', '', '', '', 'Exquisite royal heritage FRP Elephant Statue cast in high-density Fiberglass Reinforced Plastic. Showcases intricate traditional Indian ceremonial drapery details, meticulously finished in weathered bronze and gold leaf paint. Highly weather-proof and structured for grand outdoor entranceways.', 'FRP (Fiberglass Reinforced Plastic)', '', 'Dark Brown / Charcoal', 'Metallic Lacquered Finish', 'images/products/statues/frp-elephant-statue.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(27, 6, 'Radha Krishna Statue', 'radha-krishna-statue', '', '', '', '', 'Divine Radha Krishna Murti hand-carved from select single-block white alabaster marble. Highlighted with soft sky blue garments and fine gold-lining brushwork, this piece brings peaceful spiritual energy to residential altars and temples alike.', 'Premium White Alabaster Marble', '', 'Light Blue, Yellow and Green', 'Polished Gloss with Hand-painted Details', 'images/products/statues/radha-krishna-statue.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(28, 6, 'FRP Meditating Buddha Statue', 'frp-meditating-buddha-statue', '', '', '', '', 'Zen-inspired sitting Meditating Buddha Statue cast in high-grade lightweight FRP. Finished with a natural sandstone texture that perfectly mimics heavy stone block carvings without the weight, making it a stellar addition to peaceful outdoor garden walks.', 'FRP (Fiber Reinforced Plastic)', '', 'Metallic Bronze / Copper', 'Matte Stone Textured', 'images/products/statues/buddha-statue-1.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(29, 6, 'FRP Dhyana Mudra Buddha Statue', 'frp-dhyana-mudra-buddha-statue', '', '', '', '', 'Stunning Dhyana Mudra Buddha statue capturing the classic hand gesture of deep concentration. Cast using robust fiberglass resins and finished with an antique verdigris copper patina that beautifully matches outdoor flora and water fountain bodies.', 'FRP (Fiber Reinforced Plastic)', '', 'Soft Peach / Light Orange', 'Verdigris Metallic Patina', 'images/products/statues/buddha-statue-2.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(30, 6, 'FRP Meditating Shiva Statue (6ft)', 'frp-meditating-shiva-statue-6ft', '', '', '', '', 'Grand 6-foot tall representation of Lord Shiva sitting in deep Himalayan padmasana dhyāna. Engineered utilizing premium-grade, reinforced fiberglass fibers to survive intense summer sun, rainfall, and winter frost without cracking.', 'FRP (Fiber Reinforced Plastic)', '', 'Metallic Copper / Rose Gold', 'Stone Matte Wash', 'images/products/statues/shiva-1.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(31, 6, 'FRP Blessing Lord Shiva Statue', 'frp-blessing-lord-shiva-statue', '', '', '', '', 'Majestic 6-foot Lord Shiva statue showcasing the Abhaya Mudra (blessing of fearlessness). Meticulously hand-colored in warm, earthy terracotta-ochre tones, creating a highly welcoming focal point for yoga schools, health spas, and spiritual sanctuaries.', 'FRP (Fiber Reinforced Plastic)', '', 'Dark Bronze / Metallic Brown', 'Polished Hand-painted Lacquer', 'images/products/statues/shiva-2.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(32, 6, 'FRP Adiyogi Style Shiva Statue', 'frp-adiyogi-style-shiva-statue', '', '', '', '', 'Stunning modern Adiyogi-inspired Lord Shiva statue finished in a sleek, solid white tone. Blends ancient yogic iconography with contemporary geometric line carving, making it a beautiful statement piece for modern fitness studios and zen parks.', 'FRP (Fiber Reinforced Plastic)', '', 'Solid White', 'Semi-Gloss Powdered Satin', 'images/products/statues/shiva-3.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(33, 6, 'FRP Mahadev Meditation Statue', 'frp-mahadev-meditation-statue', '', '', '', '', 'A breathtaking 6-foot Mahadev meditation sculpture hand-finished in pearlescent alabaster white with subtle blue accenting. Engineered with marine-grade fiberglass resin shells, perfect for humid pool decks and harsh tropical climates.', 'FRP (Fiber Reinforced Plastic)', '', 'Sky Blue', 'Premium Semi-gloss Pearlescent', 'images/products/statues/shiva-4.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(34, 9, 'Matrix FRP Planter MX3R1', 'matrix-frp-planter-mx3r1', 'MX3R1', 'MX3R1', 'Catalog I', 'MATRIX SERIES', 'Premium Matrix FRP Planter crafted with lightweight, high-tensile Fiber Reinforced Plastic. Ideal for enhancing luxury residential spaces, corporate offices, hotels, and contemporary outdoor landscaping. Durable construction that effortlessly handles both indoor and outdoor environments.', 'FRP (Fiber Reinforced Plastic)', 'Round', 'Customizable', 'Matte', 'images/products/planters/planter34.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(35, 9, 'Matrix FRP Planter MX3R2', 'matrix-frp-planter-mx3r2', 'MX3R2', 'MX3R2', 'Catalog I', 'MATRIX SERIES', 'Premium Matrix FRP Planter crafted with lightweight, high-tensile Fiber Reinforced Plastic. Ideal for enhancing luxury residential spaces, corporate offices, hotels, and contemporary outdoor landscaping. Durable construction that effortlessly handles both indoor and outdoor environments.', 'FRP (Fiber Reinforced Plastic)', 'Round', 'Customizable', 'Matte', 'images/products/planters/planter35.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(36, 9, 'Matrix FRP Planter MX3R3', 'matrix-frp-planter-mx3r3', 'MX3R3', 'MX3R3', 'Catalog I', 'MATRIX SERIES', 'Premium Matrix FRP Planter crafted with lightweight, high-tensile Fiber Reinforced Plastic. Ideal for enhancing luxury residential spaces, corporate offices, hotels, and contemporary outdoor landscaping. Durable construction that effortlessly handles both indoor and outdoor environments.', 'FRP (Fiber Reinforced Plastic)', 'Round', 'Customizable', 'Matte', 'images/products/planters/planter36.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(37, 9, 'Matrix FRP Planter MX3R4', 'matrix-frp-planter-mx3r4', 'MX3R4', 'MX3R4', 'Catalog I', 'MATRIX SERIES', 'Premium Matrix FRP Planter crafted with lightweight, high-tensile Fiber Reinforced Plastic. Ideal for enhancing luxury residential spaces, corporate offices, hotels, and contemporary outdoor landscaping. Durable construction that effortlessly handles both indoor and outdoor environments.', 'FRP (Fiber Reinforced Plastic)', 'Round', 'Customizable', 'Matte', 'images/products/planters/planter37.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(38, 9, 'Matrix FRP Planter MX4R5', 'matrix-frp-planter-mx4r5', 'MX4R5', 'MX4R5', 'Catalog I', 'MATRIX SERIES', 'Premium Matrix FRP Planter crafted with lightweight, high-tensile Fiber Reinforced Plastic. Ideal for enhancing luxury residential spaces, corporate offices, hotels, and contemporary outdoor landscaping. Durable construction that effortlessly handles both indoor and outdoor environments.', 'FRP (Fiber Reinforced Plastic)', 'Round', 'Customizable', 'Matte', 'images/products/planters/planter38.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(39, 9, 'Matrix FRP Planter MX3O6', 'matrix-frp-planter-mx3o6', 'MX3O6', 'MX3O6', 'Catalog I', 'MATRIX SERIES', 'Premium Matrix FRP Planter crafted with lightweight, high-tensile Fiber Reinforced Plastic. Ideal for enhancing luxury residential spaces, corporate offices, hotels, and contemporary outdoor landscaping. Durable construction that effortlessly handles both indoor and outdoor environments.', 'FRP (Fiber Reinforced Plastic)', 'Oval', 'Customizable', 'Matte', 'images/products/planters/planter39.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(40, 9, 'Matrix FRP Planter MX3R7', 'matrix-frp-planter-mx3r7', 'MX3R7', 'MX3R7', 'Catalog I', 'MATRIX SERIES', 'Premium Matrix FRP Planter crafted with lightweight, high-tensile Fiber Reinforced Plastic. Ideal for enhancing luxury residential spaces, corporate offices, hotels, and contemporary outdoor landscaping. Durable construction that effortlessly handles both indoor and outdoor environments.', 'FRP (Fiber Reinforced Plastic)', 'Round', 'Customizable', 'Matte', 'images/products/planters/planter40.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sku`, `item_code`, `catalog`, `series`, `description`, `material`, `shape`, `color`, `finish`, `thumbnail`, `featured`, `status`, `created_at`, `updated_at`) VALUES
(41, 9, 'Matrix FRP Planter MX1S8', 'matrix-frp-planter-mx1s8', 'MX1S8', 'MX1S8', 'Catalog I', 'MATRIX SERIES', 'Premium Matrix FRP Planter crafted with lightweight, high-tensile Fiber Reinforced Plastic. Ideal for enhancing luxury residential spaces, corporate offices, hotels, and contemporary outdoor landscaping. Durable construction that effortlessly handles both indoor and outdoor environments.', 'FRP (Fiber Reinforced Plastic)', 'Square', 'Customizable', 'Matte', 'images/products/planters/planter41.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(42, 9, 'Matrix FRP Planter MX2S9', 'matrix-frp-planter-mx2s9', 'MX2S9', 'MX2S9', 'Catalog I', 'MATRIX SERIES', 'Premium Matrix FRP Planter crafted with lightweight, high-tensile Fiber Reinforced Plastic. Ideal for enhancing luxury residential spaces, corporate offices, hotels, and contemporary outdoor landscaping. Durable construction that effortlessly handles both indoor and outdoor environments.', 'FRP (Fiber Reinforced Plastic)', 'Square', 'Customizable', 'Matte', 'images/products/planters/planter42.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(43, 9, 'Matrix FRP Planter MX2R37', 'matrix-frp-planter-mx2r37', 'MX2R37', 'MX2R37', 'Catalog II', 'MATRIX SERIES', 'Premium Matrix FRP Planter crafted with lightweight, high-tensile Fiber Reinforced Plastic. Ideal for enhancing luxury residential spaces, corporate offices, hotels, and contemporary outdoor landscaping. Durable construction that effortlessly handles both indoor and outdoor environments.', 'FRP (Fiber Reinforced Plastic)', 'Round', 'Customizable', 'Matte', 'images/products/planters/planter43.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(44, 9, 'Rock FRP Planter RC4S10', 'rock-frp-planter-rc4s10', 'RC4S10', 'RC4S10', 'Catalog I', 'ROCK SERIES', 'Premium Rock FRP Planter capturing a detailed organic texture via sturdy Fiber Reinforced Plastic. Perfect for adding a rustic, natural aesthetic to outdoor patios, themed rock gardens, resort landscapes, and modern bohemian indoor spaces.', 'FRP (Fiber Reinforced Plastic)', 'Square', 'Customizable', 'Stone Texture', 'images/products/planters/planter44.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(45, 9, 'Rock FRP Planter RC3R11', 'rock-frp-planter-rc3r11', 'RC3R11', 'RC3R11', 'Catalog I', 'ROCK SERIES', 'Premium Rock FRP Planter capturing a detailed organic texture via sturdy Fiber Reinforced Plastic. Perfect for adding a rustic, natural aesthetic to outdoor patios, themed rock gardens, resort landscapes, and modern bohemian indoor spaces.', 'FRP (Fiber Reinforced Plastic)', 'Round', 'Customizable', 'Stone Texture', 'images/products/planters/planter45.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(46, 9, 'Rock FRP Planter RC3R12', 'rock-frp-planter-rc3r12', 'RC3R12', 'RC3R12', 'Catalog I', 'ROCK SERIES', 'Premium Rock FRP Planter capturing a detailed organic texture via sturdy Fiber Reinforced Plastic. Perfect for adding a rustic, natural aesthetic to outdoor patios, themed rock gardens, resort landscapes, and modern bohemian indoor spaces.', 'FRP (Fiber Reinforced Plastic)', 'Round', 'Customizable', 'Stone Texture', 'images/products/planters/planter46.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(47, 9, 'Rock FRP Planter RC4R13', 'rock-frp-planter-rc4r13', 'RC4R13', 'RC4R13', 'Catalog I', 'ROCK SERIES', 'Premium Rock FRP Planter capturing a detailed organic texture via sturdy Fiber Reinforced Plastic. Perfect for adding a rustic, natural aesthetic to outdoor patios, themed rock gardens, resort landscapes, and modern bohemian indoor spaces.', 'FRP (Fiber Reinforced Plastic)', 'Round', 'Customizable', 'Stone Texture', 'images/products/planters/planter47.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(48, 9, 'Rock FRP Planter RC3R14', 'rock-frp-planter-rc3r14', 'RC3R14', 'RC3R14', 'Catalog I', 'ROCK SERIES', 'Premium Rock FRP Planter capturing a detailed organic texture via sturdy Fiber Reinforced Plastic. Perfect for adding a rustic, natural aesthetic to outdoor patios, themed rock gardens, resort landscapes, and modern bohemian indoor spaces.', 'FRP (Fiber Reinforced Plastic)', 'Round', 'Customizable', 'Stone Texture', 'images/products/planters/planter48.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(49, 9, 'Rock FRP Planter RC4R15', 'rock-frp-planter-rc4r15', 'RC4R15', 'RC4R15', 'Catalog I', 'ROCK SERIES', 'Premium Rock FRP Planter capturing a detailed organic texture via sturdy Fiber Reinforced Plastic. Perfect for adding a rustic, natural aesthetic to outdoor patios, themed rock gardens, resort landscapes, and modern bohemian indoor spaces.', 'FRP (Fiber Reinforced Plastic)', 'Round', 'Customizable', 'Stone Texture', 'images/products/planters/planter49.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(50, 9, 'Rock FRP Planter RC4R16', 'rock-frp-planter-rc4r16', 'RC4R16', 'RC4R16', 'Catalog I', 'ROCK SERIES', 'Premium Rock FRP Planter capturing a detailed organic texture via sturdy Fiber Reinforced Plastic. Perfect for adding a rustic, natural aesthetic to outdoor patios, themed rock gardens, resort landscapes, and modern bohemian indoor spaces.', 'FRP (Fiber Reinforced Plastic)', 'Round', 'Customizable', 'Stone Texture', 'images/products/planters/planter50.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(51, 9, 'Rock FRP Planter RC3R17', 'rock-frp-planter-rc3r17', 'RC3R17', 'RC3R17', 'Catalog I', 'ROCK SERIES', 'Premium Rock FRP Planter capturing a detailed organic texture via sturdy Fiber Reinforced Plastic. Perfect for adding a rustic, natural aesthetic to outdoor patios, themed rock gardens, resort landscapes, and modern bohemian indoor spaces.', 'FRP (Fiber Reinforced Plastic)', 'Round', 'Customizable', 'Stone Texture', 'images/products/planters/planter51.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(52, 9, 'Rock FRP Planter RC4S18', 'rock-frp-planter-rc4s18', 'RC4S18', 'RC4S18', 'Catalog I', 'ROCK SERIES', 'Premium Rock FRP Planter capturing a detailed organic texture via sturdy Fiber Reinforced Plastic. Perfect for adding a rustic, natural aesthetic to outdoor patios, themed rock gardens, resort landscapes, and modern bohemian indoor spaces.', 'FRP (Fiber Reinforced Plastic)', 'Square', 'Customizable', 'Stone Texture', 'images/products/planters/planter52.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(53, 9, 'Rough Stone FRP Planter RO4R19', 'rough-stone-frp-planter-ro4r19', 'RO4R19', 'RO4R19', 'Catalog I', 'ROUGH STONE SERIES', 'Premium Rough Stone FRP Planter delivering a rugged, coarse stone aesthetic using durable Fiber Reinforced Plastic. Designed to seamlessly withstand outdoor exposure in courtyard gardens, architectural entryways, and texturally rich interiors.', 'FRP (Fiber Reinforced Plastic)', 'Round', 'Customizable', 'Stone Texture', 'images/products/planters/planter53.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(54, 9, 'Rough Stone FRP Planter RO4S20', 'rough-stone-frp-planter-ro4s20', 'RO4S20', 'RO4S20', 'Catalog I', 'ROUGH STONE SERIES', 'Premium Rough Stone FRP Planter delivering a rugged, coarse stone aesthetic using durable Fiber Reinforced Plastic. Designed to seamlessly withstand outdoor exposure in courtyard gardens, architectural entryways, and texturally rich interiors.', 'FRP (Fiber Reinforced Plastic)', 'Square', 'Customizable', 'Stone Texture', 'images/products/planters/planter54.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(55, 9, 'Rough Stone FRP Planter RO4R21', 'rough-stone-frp-planter-ro4r21', 'RO4R21', 'RO4R21', 'Catalog I', 'ROUGH STONE SERIES', 'Premium Rough Stone FRP Planter delivering a rugged, coarse stone aesthetic using durable Fiber Reinforced Plastic. Designed to seamlessly withstand outdoor exposure in courtyard gardens, architectural entryways, and texturally rich interiors.', 'FRP (Fiber Reinforced Plastic)', 'Round', 'Customizable', 'Stone Texture', 'images/products/planters/planter55.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(56, 9, 'Rough Stone FRP Planter RO3R22', 'rough-stone-frp-planter-ro3r22', 'RO3R22', 'RO3R22', 'Catalog I', 'ROUGH STONE SERIES', 'Premium Rough Stone FRP Planter delivering a rugged, coarse stone aesthetic using durable Fiber Reinforced Plastic. Designed to seamlessly withstand outdoor exposure in courtyard gardens, architectural entryways, and texturally rich interiors.', 'FRP (Fiber Reinforced Plastic)', 'Round', 'Customizable', 'Stone Texture', 'images/products/planters/planter56.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(57, 9, 'Rough Stone FRP Planter RO4R23', 'rough-stone-frp-planter-ro4r23', 'RO4R23', 'RO4R23', 'Catalog I', 'ROUGH STONE SERIES', 'Premium Rough Stone FRP Planter delivering a rugged, coarse stone aesthetic using durable Fiber Reinforced Plastic. Designed to seamlessly withstand outdoor exposure in courtyard gardens, architectural entryways, and texturally rich interiors.', 'FRP (Fiber Reinforced Plastic)', 'Round', 'Customizable', 'Stone Texture', 'images/products/planters/planter57.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(58, 9, 'Rough Stone FRP Planter RO3R24', 'rough-stone-frp-planter-ro3r24', 'RO3R24', 'RO3R24', 'Catalog I', 'ROUGH STONE SERIES', 'Premium Rough Stone FRP Planter delivering a rugged, coarse stone aesthetic using durable Fiber Reinforced Plastic. Designed to seamlessly withstand outdoor exposure in courtyard gardens, architectural entryways, and texturally rich interiors.', 'FRP (Fiber Reinforced Plastic)', 'Round', 'Customizable', 'Stone Texture', 'images/products/planters/planter58.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(59, 9, 'Rough Stone FRP Planter RO3R25', 'rough-stone-frp-planter-ro3r25', 'RO3R25', 'RO3R25', 'Catalog I', 'ROUGH STONE SERIES', 'Premium Rough Stone FRP Planter delivering a rugged, coarse stone aesthetic using durable Fiber Reinforced Plastic. Designed to seamlessly withstand outdoor exposure in courtyard gardens, architectural entryways, and texturally rich interiors.', 'FRP (Fiber Reinforced Plastic)', 'Round', 'Customizable', 'Stone Texture', 'images/products/planters/planter59.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(60, 9, 'Rough Stone FRP Planter RO2O26', 'rough-stone-frp-planter-ro2o26', 'RO2O26', 'RO2O26', 'Catalog I', 'ROUGH STONE SERIES', 'Premium Rough Stone FRP Planter delivering a rugged, coarse stone aesthetic using durable Fiber Reinforced Plastic. Designed to seamlessly withstand outdoor exposure in courtyard gardens, architectural entryways, and texturally rich interiors.', 'FRP (Fiber Reinforced Plastic)', 'Oval', 'Customizable', 'Stone Texture', 'images/products/planters/planter60.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(61, 9, 'Rough Stone FRP Planter RO2P27', 'rough-stone-frp-planter-ro2p27', 'RO2P27', 'RO2P27', 'Catalog I', 'ROUGH STONE SERIES', 'Premium Rough Stone FRP Planter delivering a rugged, coarse stone aesthetic using durable Fiber Reinforced Plastic. Designed to seamlessly withstand outdoor exposure in courtyard gardens, architectural entryways, and texturally rich interiors.', 'FRP (Fiber Reinforced Plastic)', 'Rectangle', 'Customizable', 'Stone Texture', 'images/products/planters/planter61.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(62, 9, 'Royal FRP Planter RY4R28', 'royal-frp-planter-ry4r28', 'RY4R28', 'RY4R28', 'Catalog I', 'ROYAL SERIES', 'Exquisite Royal FRP Planter exhibiting a prestigious stately design achieved through premium-grade Fiber Reinforced Plastic. The ultimate architectural statement piece for luxury estate entryways, upscale hotel lobbies, banquets, and grand patios.', 'FRP (Fiber Reinforced Plastic)', 'Round', 'Customizable', 'Premium Matte', 'images/products/planters/planter62.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(63, 9, 'Royal FRP Planter RY3O29', 'royal-frp-planter-ry3o29', 'RY3O29', 'RY3O29', 'Catalog I', 'ROYAL SERIES', 'Exquisite Royal FRP Planter exhibiting a prestigious stately design achieved through premium-grade Fiber Reinforced Plastic. The ultimate architectural statement piece for luxury estate entryways, upscale hotel lobbies, banquets, and grand patios.', 'FRP (Fiber Reinforced Plastic)', 'Oval', 'Customizable', 'Premium Matte', 'images/products/planters/planter63.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(64, 9, 'Royal FRP Planter RY4R30', 'royal-frp-planter-ry4r30', 'RY4R30', 'RY4R30', 'Catalog I', 'ROYAL SERIES', 'Exquisite Royal FRP Planter exhibiting a prestigious stately design achieved through premium-grade Fiber Reinforced Plastic. The ultimate architectural statement piece for luxury estate entryways, upscale hotel lobbies, banquets, and grand patios.', 'FRP (Fiber Reinforced Plastic)', 'Round', 'Customizable', 'Premium Matte', 'images/products/planters/planter64.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(65, 9, 'Royal FRP Planter RY4R31', 'royal-frp-planter-ry4r31', 'RY4R31', 'RY4R31', 'Catalog I', 'ROYAL SERIES', 'Exquisite Royal FRP Planter exhibiting a prestigious stately design achieved through premium-grade Fiber Reinforced Plastic. The ultimate architectural statement piece for luxury estate entryways, upscale hotel lobbies, banquets, and grand patios.', 'FRP (Fiber Reinforced Plastic)', 'Round', 'Customizable', 'Premium Matte', 'images/products/planters/planter65.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(66, 9, 'Timber FRP Planter TB4R32', 'timber-frp-planter-tb4r32', 'TB4R32', 'TB4R32', 'Catalog I', 'TIMBER SERIES', 'Natural Timber FRP Planter masterfully mimicking detailed organic wood grain utilizing long-lasting Fiber Reinforced Plastic. Brings the warm aesthetic of real timber to balconies, botanical spaces, porches, and decks without the risk of rotting or splitting.', 'FRP (Fiber Reinforced Plastic)', 'Round', 'Customizable', 'Wood Texture', 'images/products/planters/planter66.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(67, 9, 'Tiny FRP Planter TY3R33', 'tiny-frp-planter-ty3r33', 'TY3R33', 'TY3R33', 'Catalog I', 'TINY SERIES', 'Natural Tiny FRP Planter masterfully mimicking detailed organic wood grain utilizing long-lasting Fiber Reinforced Plastic. Brings the warm aesthetic of real timber to compact spaces, balconies, botanical nooks, porches, and decks without the risk of rotting or splitting.', 'FRP (Fiber Reinforced Plastic)', 'Round', 'Customizable', 'Wood Texture', 'images/products/planters/planter67.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(68, 9, 'Velvet FRP Planter VT4R34', 'velvet-frp-planter-vt4r34', 'VT4R34', 'VT4R34', 'Catalog II', 'VELVET SERIES', 'Premium Velvet Series FRP planter featuring a contemporary stone texture finish. Designed for indoor and outdoor landscaping while offering exceptional durability and lightweight construction.', 'FRP (Fiber Reinforced Plastic)', 'Round', 'Customizable', 'Stone Texture', 'images/products/planters/planter68.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(69, 9, 'Velvet FRP Planter VT4R35', 'velvet-frp-planter-vt4r35', 'VT4R35', 'VT4R35', 'Catalog II', 'VELVET SERIES', 'Elegant tall Velvet Series FRP planter designed to create striking landscape focal points with superior durability and weather resistance.', 'FRP (Fiber Reinforced Plastic)', 'Round', 'Customizable', 'Stone Texture', 'images/products/planters/planter69.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(70, 9, 'Velvet FRP Planter VT3RE36', 'velvet-frp-planter-vt3re36', 'VT3RE36', 'VT3RE36', 'Catalog II', 'VELVET SERIES', 'Modern rectangular Velvet Series FRP planter with contemporary styling, ideal for commercial landscapes, balconies and premium outdoor spaces.', 'FRP (Fiber Reinforced Plastic)', 'Rectangular', 'Customizable', 'Stone Texture', 'images/products/planters/planter70.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(71, 9, 'Matrix FRP Planter MX3R38', 'matrix-frp-planter-mx3r38', 'MX3R38', 'MX3R38', 'Catalog II', 'MATRIX SERIES', 'Modern Matrix Series FRP planter with a contemporary stone texture finish. Crafted from premium Fiber Reinforced Plastic for lightweight handling, exceptional durability, and long-lasting outdoor performance.', 'FRP (Fiber Reinforced Plastic)', 'Round', 'Customizable', 'Stone Texture', 'images/products/planters/planter71.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(72, 9, 'Matrix FRP Planter MX3R39', 'matrix-frp-planter-mx3r39', 'MX3R39', 'MX3R39', 'Catalog II', 'MATRIX SERIES', 'Elegant Matrix Series FRP planter designed with a sophisticated stone texture finish. Ideal for residential gardens, commercial landscapes, terraces, balconies, and entrance décor.', 'FRP (Fiber Reinforced Plastic)', 'Round', 'Customizable', 'Stone Texture', 'images/products/planters/planter72.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(73, 9, 'Matrix FRP Planter MX3R40', 'matrix-frp-planter-mx3r40', 'MX3R40', 'MX3R40', 'Catalog II', 'MATRIX SERIES', 'Contemporary Matrix Series FRP planter featuring a clean geometric profile with a premium stone texture finish. Manufactured using high-quality Fiber Reinforced Plastic to provide superior durability, lightweight handling, and long-lasting performance for residential and commercial landscaping projects.', 'FRP (Fiber Reinforced Plastic)', 'Round', 'Customizable', 'Stone Texture', 'images/products/planters/planter73.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(74, 9, 'Matrix FRP Planter MX4R41', 'matrix-frp-planter-mx4r41', 'MX4R41', 'MX4R41', 'Catalog II', 'MATRIX SERIES', 'Premium Matrix Series FRP planter featuring a contemporary stone texture finish. Manufactured using high-quality Fiber Reinforced Plastic to deliver outstanding durability, lightweight construction, and long-lasting performance for residential and commercial landscapes.', 'FRP (Fiber Reinforced Plastic)', 'Round', 'Customizable', 'Stone Texture', 'images/products/planters/planter74.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(75, 9, 'Matrix FRP Planter MX3R42', 'matrix-frp-planter-mx3r42', 'MX3R42', 'MX3R42', 'Catalog II', 'MATRIX SERIES', 'Elegant Matrix Series FRP planter with a refined stone texture finish. Designed for modern indoor and outdoor spaces, this lightweight yet durable planter offers excellent weather resistance and timeless contemporary styling.', 'FRP (Fiber Reinforced Plastic)', 'Round', 'Customizable', 'Stone Texture', 'images/products/planters/planter75.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(76, 9, 'Matrix FRP Planter MX3R43', 'matrix-frp-planter-mx3r43', 'MX3R43', 'MX3R43', 'Catalog II', 'MATRIX SERIES', 'Modern Matrix Series FRP planter with a premium stone texture finish, designed to complement contemporary indoor and outdoor spaces. Made from high-quality Fiber Reinforced Plastic, it offers exceptional durability, lightweight handling, UV resistance, and long-lasting performance in all weather conditions.', 'FRP (Fiber Reinforced Plastic)', 'Round', 'Customizable', 'Stone Texture', 'images/products/planters/planter76.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02');
INSERT INTO `products` (`id`, `category_id`, `name`, `slug`, `sku`, `item_code`, `catalog`, `series`, `description`, `material`, `shape`, `color`, `finish`, `thumbnail`, `featured`, `status`, `created_at`, `updated_at`) VALUES
(77, 9, 'Matrix FRP Planter MX4S44', 'matrix-frp-planter-mx4s44', 'MX4S44', 'MX4S44', 'Catalog II', 'MATRIX SERIES', 'Premium Matrix Series FRP square planter featuring a clean geometric design with an elegant stone texture finish. Manufactured from high-quality Fiber Reinforced Plastic, it provides excellent durability, lightweight construction, UV resistance, and weather protection, making it ideal for residential gardens, commercial landscapes, patios, entrances, and interior décor.', 'FRP (Fiber Reinforced Plastic)', 'Square', 'Customizable', 'Stone Texture', 'images/products/planters/planter77.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(78, 9, 'Matrix FRP Planter MX3R45', 'matrix-frp-planter-mx3r45', 'MX3R45', 'MX3R45', 'Catalog II', 'MATRIX SERIES', 'Elegant Matrix Series FRP planter featuring a tall contemporary profile with a premium stone texture finish. Crafted from high-quality Fiber Reinforced Plastic, it is lightweight, durable, UV resistant, and suitable for both indoor and outdoor landscaping applications.', 'FRP (Fiber Reinforced Plastic)', 'Round', 'Customizable', 'Stone Texture', 'images/products/planters/planter78.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(79, 9, 'Matrix FRP Planter MX4R46', 'matrix-frp-planter-mx4r46', 'MX4R46', 'MX4R46', 'Catalog II', 'MATRIX SERIES', 'Premium Matrix Series FRP planter featuring a contemporary stone texture finish. Manufactured using high-quality Fiber Reinforced Plastic, it offers excellent durability, lightweight construction, UV resistance, and weatherproof performance, making it suitable for gardens, patios, balconies, commercial landscapes, and interior décor.', 'FRP (Fiber Reinforced Plastic)', 'Round', 'Customizable', 'Stone Texture', 'images/products/planters/planter79.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(80, 9, 'Matrix FRP Planter MX3R47', 'matrix-frp-planter-mx3r47', 'MX3R47', 'MX3R47', 'Catalog II', 'MATRIX SERIES', 'Stylish Matrix Series FRP planter featuring a sleek vertical profile with a premium stone texture finish. Manufactured from high-quality Fiber Reinforced Plastic, it combines lightweight construction, exceptional durability, UV protection, and weather resistance, making it ideal for residential gardens, commercial landscapes, entrances, patios, balconies, and indoor décor.', 'FRP (Fiber Reinforced Plastic)', 'Round', 'Customizable', 'Stone Texture', 'images/products/planters/planter80.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(81, 9, 'Rock FRP Planter RC4R49', 'rock-frp-planter-rc4r49', 'RC4R49', 'RC4R49', 'Catalog II', 'ROCK SERIES', 'Premium Rock Series FRP planter featuring an authentic rock texture finish that blends naturally into landscape designs. Manufactured from high-quality Fiber Reinforced Plastic, it offers exceptional durability, lightweight construction, UV resistance, and all-weather performance for both indoor and outdoor applications.', 'FRP (Fiber Reinforced Plastic)', 'Round', 'Customizable', 'Rock Texture', 'images/products/planters/planter81.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(82, 9, 'Rough Stone FRP Planter RO3R51', 'rough-stone-frp-planter-ro3r51', 'RO3R51', 'RO3R51', 'Catalog II', 'ROUGH STONE SERIES', 'Premium Rough Stone Series FRP planter featuring an authentic rough stone texture that adds a natural aesthetic to gardens, patios, commercial landscapes, and indoor spaces. Crafted from high-quality Fiber Reinforced Plastic, it offers exceptional durability, lightweight construction, UV resistance, and long-lasting all-weather performance.', 'FRP (Fiber Reinforced Plastic)', 'Round', 'Customizable', 'Rough Stone Texture', 'images/products/planters/planter82.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(83, 9, 'Rough Stone FRP Planter RO3R52', 'rough-stone-frp-planter-ro3r52', 'RO3R52', 'RO3R52', 'Catalog II', 'ROUGH STONE SERIES', 'Premium Rough Stone Series FRP planter featuring a realistic rough stone texture that complements modern and natural landscapes. Manufactured using high-quality Fiber Reinforced Plastic, it offers exceptional durability, lightweight construction, UV resistance, and weatherproof performance, making it ideal for residential gardens, commercial landscapes, terraces, patios, and indoor décor.', 'FRP (Fiber Reinforced Plastic)', 'Round', 'Customizable', 'Rough Stone Texture', 'images/products/planters/planter83.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(84, 9, 'Rough Stone FRP Planter RO3R53', 'rough-stone-frp-planter-ro3r53', 'RO3R53', 'RO3R53', 'Catalog II', 'ROUGH STONE SERIES', 'Premium Rough Stone Series FRP planter featuring a natural rough stone texture that blends beautifully with contemporary and traditional landscapes. Manufactured from high-quality Fiber Reinforced Plastic, it offers exceptional durability, lightweight construction, UV protection, and weather resistance for long-lasting indoor and outdoor use.', 'FRP (Fiber Reinforced Plastic)', 'Round', 'Customizable', 'Rough Stone Texture', 'images/products/planters/planter84.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(85, 9, 'Royal FRP Planter RY3R54', 'royal-frp-planter-ry3r54', 'RY3R54', 'RY3R54', 'Catalog II', 'ROYAL SERIES', 'Elegant Royal Series FRP planter featuring a premium royal stone texture finish that adds sophistication to residential and commercial landscapes. Crafted from high-quality Fiber Reinforced Plastic, it offers lightweight construction, exceptional durability, UV resistance, and all-weather performance for indoor and outdoor applications.', 'FRP (Fiber Reinforced Plastic)', 'Round', 'Customizable', 'Royal Stone Texture', 'images/products/planters/planter85.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(86, 9, 'Royal FRP Planter RY3R55', 'royal-frp-planter-ry3r55', 'RY3R55', 'RY3R55', 'Catalog II', 'ROYAL SERIES', 'Elegant Royal Series FRP planter featuring a premium royal stone texture finish that enhances modern and traditional landscapes. Manufactured from high-quality Fiber Reinforced Plastic, it provides lightweight construction, superior durability, UV protection, and excellent weather resistance for long-lasting indoor and outdoor use.', 'FRP (Fiber Reinforced Plastic)', 'Round', 'Customizable', 'Royal Stone Texture', 'images/products/planters/planter86.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(87, 9, 'Royal FRP Planter RY3R56', 'royal-frp-planter-ry3r56', 'RY3R56', 'RY3R56', 'Catalog II', 'ROYAL SERIES', 'Premium Royal Series FRP planter featuring an elegant royal stone texture finish that adds sophistication to residential gardens, commercial landscapes, patios, balconies, and indoor décor. Manufactured from high-quality Fiber Reinforced Plastic, it combines lightweight construction, exceptional durability, UV resistance, and weatherproof performance for long-lasting beauty.', 'FRP (Fiber Reinforced Plastic)', 'Round', 'Customizable', 'Royal Stone Texture', 'images/products/planters/planter87.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(88, 9, 'Royal FRP Planter RY3R57', 'royal-frp-planter-ry3r57', 'RY3R57', 'RY3R57', 'Catalog II', 'ROYAL SERIES', 'Premium Royal Series FRP planter featuring a luxurious royal stone texture finish with a wide, shallow profile that enhances contemporary and classic landscape designs. Crafted from high-quality Fiber Reinforced Plastic, it provides excellent durability, lightweight construction, UV protection, and weather resistance for long-lasting indoor and outdoor use.', 'FRP (Fiber Reinforced Plastic)', 'Round', 'Customizable', 'Royal Stone Texture', 'images/products/planters/planter88.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(89, 9, 'Royal FRP Planter RY3R58', 'royal-frp-planter-ry3r58', 'RY3R58', 'RY3R58', 'Catalog II', 'ROYAL SERIES', 'Premium Royal Series FRP planter featuring a sophisticated royal stone texture finish that enhances modern and classic landscapes alike. Manufactured from high-quality Fiber Reinforced Plastic, it offers lightweight construction, exceptional durability, UV resistance, and weatherproof performance, making it ideal for gardens, patios, balconies, commercial spaces, and indoor décor.', 'FRP (Fiber Reinforced Plastic)', 'Round', 'Customizable', 'Royal Stone Texture', 'images/products/planters/planter89.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(90, 9, 'Royal FRP Planter RY4S59', 'royal-frp-planter-ry4s59', 'RY4S59', 'RY4S59', 'Catalog II', 'ROYAL SERIES', 'Premium Royal Series FRP square planter featuring a luxurious royal stone texture finish. Crafted from high-quality Fiber Reinforced Plastic, it offers exceptional durability, lightweight construction, UV protection, and weather resistance, making it ideal for premium residential, hospitality, commercial, and landscape applications.', 'FRP (Fiber Reinforced Plastic)', 'Square', 'Customizable', 'Royal Stone Texture', 'images/products/planters/planter90.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(91, 9, 'Royal FRP Planter RY4R60', 'royal-frp-planter-ry4r60', 'RY4R60', 'RY4R60', 'Catalog II', 'ROYAL SERIES', 'Premium Royal Series FRP planter featuring a luxurious royal stone texture finish. Manufactured using high-quality Fiber Reinforced Plastic, it offers lightweight construction, exceptional durability, UV protection, and weather resistance, making it ideal for residential gardens, commercial landscapes, hotels, patios, entrances, and indoor décor.', 'FRP (Fiber Reinforced Plastic)', 'Round', 'Customizable', 'Royal Stone Texture', 'images/products/planters/planter91.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(92, 9, 'Velvet FRP Planter VT4R61', 'velvet-frp-planter-vt4r61', 'VT4R61', 'VT4R61', 'Catalog II', 'VELVET SERIES', 'Premium Velvet Series FRP planter featuring a refined velvet texture finish that enhances both contemporary and luxury landscapes. Manufactured from high-quality Fiber Reinforced Plastic, it offers lightweight construction, exceptional durability, UV resistance, and weatherproof performance, making it ideal for gardens, patios, balconies, hotels, commercial spaces, and indoor décor.', 'FRP (Fiber Reinforced Plastic)', 'Round', 'Customizable', 'Velvet Texture', 'images/products/planters/planter92.webp', 0, 1, '2026-07-18 12:54:02', '2026-07-18 12:54:02'),
(93, 9, 'Velvet FRP Planter VT3R62', 'velvet-frp-planter-vt3r62', 'VT3R62', 'VT3R62', 'Catalog II', 'VELVET SERIES', 'Premium Velvet Series FRP planter featuring a sophisticated velvet texture finish that complements contemporary and luxury landscapes. Crafted from high-quality Fiber Reinforced Plastic, it provides lightweight construction, superior durability, UV protection, and excellent weather resistance, making it ideal for residential gardens, commercial spaces, patios, balconies, and indoor décor.', 'FRP (Fiber Reinforced Plastic)', 'Round', 'Customizable', 'Velvet Texture', 'images/products/planters/planter93.webp', 0, 1, '2026-07-18 12:54:03', '2026-07-18 12:54:03'),
(94, 9, 'Velvet FRP Planter VT3R63', 'velvet-frp-planter-vt3r63', 'VT3R63', 'VT3R63', 'Catalog II', 'VELVET SERIES', 'Premium Velvet Series FRP planter featuring an elegant velvet texture finish that blends modern aesthetics with lasting durability. Manufactured from high-quality Fiber Reinforced Plastic, it offers lightweight construction, UV protection, weather resistance, and superior strength, making it suitable for residential gardens, commercial landscapes, patios, balconies, hotels, and indoor décor.', 'FRP (Fiber Reinforced Plastic)', 'Round', 'Customizable', 'Velvet Texture', 'images/products/planters/planter94.webp', 0, 1, '2026-07-18 12:54:03', '2026-07-18 12:54:03'),
(95, 9, 'Velvet FRP Planter VT3R64', 'velvet-frp-planter-vt3r64', 'VT3R64', 'VT3R64', 'Catalog II', 'VELVET SERIES', 'Premium Velvet Series FRP planter featuring a luxurious velvet texture finish that blends modern elegance with exceptional durability. Manufactured from high-quality Fiber Reinforced Plastic, it offers lightweight construction, UV protection, weather resistance, and long-lasting performance for residential gardens, commercial landscapes, patios, balconies, hotels, and indoor décor.', 'FRP (Fiber Reinforced Plastic)', 'Round', 'Customizable', 'Velvet Texture', 'images/products/planters/planter95.webp', 0, 1, '2026-07-18 12:54:03', '2026-07-18 12:54:03');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `products`
--
ALTER TABLE `products`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `slug` (`slug`),
  ADD KEY `category_id` (`category_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `products`
--
ALTER TABLE `products`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=100;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `products`
--
ALTER TABLE `products`
  ADD CONSTRAINT `products_ibfk_1` FOREIGN KEY (`category_id`) REFERENCES `categories` (`id`) ON DELETE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
